name: SwiftPMDemo
options:
  bundleIdPrefix: com.swiftpmdemo
  deploymentTarget:
    iOS: 15.0

targets:
  SwiftPMDemoApp:
    type: application
    platform: iOS
    sources:
      - iOS
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.swiftpmdemo.app
        INFOPLIST_FILE: iOS/Info.plist
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        TARGETED_DEVICE_FAMILY: "1,2"
        SWIFT_VERSION: 5.0
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
    # dependencies:
    #   - package: FugaFactory
    #   - package: Printer

# packages:
#   FugaFactory:
#     path: ../Sources/FugaFactory
#   Printer:
#     path: ../Sources/Printer

schemes:
  SwiftPMDemoApp:
    build:
      targets:
        SwiftPMDemoApp: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
